### ISSUE TITLE
readme video points to a dead link

### ISSUE THREAD

**Issue by flbn** [NSAntoine/Shiranui#1]
^^ title, this looks cool. would like to see the demo 😃

**Comment by NSAntoine** [comment]
What about this?
https://github.com/NSAntoine/Shiranui/assets/48022799/f760044d-7ddb-4731-9c30-2671b3375622

**Comment by NSAntoine** [comment]
The video is uploaded on twitter as well https://x.com/coreserena/status/1731360670619172941?s=46&t=ehEZ4NJKohnXHF5VKAQuTA

**Comment by flbn** [comment]
ahhh hell yeah this is awesome, thanks. will close :)
